CREATE TABLE IF NOT EXISTS tb_stock_investor_invest_accumulation (
    stk_cd VARCHAR(20) NOT NULL,
    dt DATE NOT NULL,
    sector VARCHAR(50),
    category1 VARCHAR(50),
    category2 VARCHAR(50),
    category3 VARCHAR(50),

    ind_invsr BIGINT,
    frgnr_invsr BIGINT,
    orgn BIGINT,
    fnnc_invt BIGINT,
    insrnc BIGINT,
    invtrt BIGINT,
    etc_fnnc BIGINT,
    bank BIGINT,
    penfnd_etc BIGINT,
    samo_fund BIGINT,
    natn BIGINT,
    etc_corp BIGINT,
    natfor BIGINT,
    frgnr_invsr_orgn BIGINT,

    ind_invsr_net_buy_qty BIGINT,
    frgnr_invsr_net_buy_qty BIGINT,
    orgn_net_buy_qty BIGINT,
    fnnc_invt_net_buy_qty BIGINT,
    insrnc_net_buy_qty BIGINT,
    invtrt_net_buy_qty BIGINT,
    etc_fnnc_net_buy_qty BIGINT,
    bank_net_buy_qty BIGINT,
    penfnd_etc_net_buy_qty BIGINT,
    samo_fund_net_buy_qty BIGINT,
    natn_net_buy_qty BIGINT,
    etc_corp_net_buy_qty BIGINT,
    natfor_net_buy_qty BIGINT,
    frgnr_invsr_orgn_net_buy_qty BIGINT,

    ind_invsr_net_buy_amount BIGINT,
    frgnr_invsr_net_buy_amount BIGINT,
    orgn_net_buy_amount BIGINT,
    fnnc_invt_net_buy_amount BIGINT,
    insrnc_net_buy_amount BIGINT,
    invtrt_net_buy_amount BIGINT,
    etc_fnnc_net_buy_amount BIGINT,
    bank_net_buy_amount BIGINT,
    penfnd_etc_net_buy_amount BIGINT,
    samo_fund_net_buy_amount BIGINT,
    natn_net_buy_amount BIGINT,
    etc_corp_net_buy_amount BIGINT,
    natfor_net_buy_amount BIGINT,
    frgnr_invsr_orgn_net_buy_amount BIGINT,

    reg_dt TIMESTAMP DEFAULT NOW(),
    upd_dt TIMESTAMP,

    PRIMARY KEY (stk_cd, dt)
);

CREATE INDEX idx_accumulation_stk_dt ON tb_stock_investor_invest_accumulation(stk_cd, dt);
